version: "3.3"

services:
  php:
    image: wodby/drupal-php:5.6-dev-4.9.0
    container_name: "${PROJECT_NAME}_php"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_DRIVER: mysql
      COLUMNS: 80
    volumes:
      - ./public_html:/var/www/html:cached

  apache:
    image: wodby/apache:2.4-4.0.2
    container_name: "${PROJECT_NAME}_apache"
    depends_on:
      - php
    ports:
      - 80:80
    environment:
      APACHE_LOG_LEVEL: debug
      APACHE_BACKEND_HOST: php
      APACHE_VHOST_PRESET: php
      APACHE_DOCUMENT_ROOT: /var/www/html
    volumes:
      - ./public_html:/var/www/html:cached

  mysql:
    image: mysql:5.7
    container_name: "${PROJECT_NAME}_mysql"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somedpupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal

  # pma:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: "${PROJECT_NAME}_pma"
  #   environment:
  #     PMA_HOST: $DB_HOST
  #     PMA_USER: $DB_USER
  #     PMA_PASSWORD: $DB_PASSWORD
  #     PHP_UPLOAD_MAX_FILESIZE: 1G
  #     PHP_MAX_INPUT_VARS: 1G
  #   ports:
  #     - 8080:80
volumes:
  db_data:
